import { StyleSheet } from 'react-native';
import { COLORS, SPACING, RADIUS, FONT_SIZE, FONT_WEIGHT } from '../../constants';

export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background.main,
  },
  headerView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary.main,
  },
  contentView: {
    flex: 3,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xl,
    backgroundColor: COLORS.background.card,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    marginTop: -30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
  },
  footerView: {
    flex: 1,
    padding: SPACING.lg,
    backgroundColor: COLORS.background.card,
  },
  title: {
    fontSize: FONT_SIZE.xxxl,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.text.light,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    marginBottom: SPACING.sm,
  },
  subtitle: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.text.primary,
    marginBottom: SPACING.lg,
  },
  textInput: {
    height: 50,
    width: '100%',
    borderWidth: 1,
    borderColor: COLORS.border.main,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    fontSize: FONT_SIZE.md,
    backgroundColor: '#f9f9f9',
  },
  buttonContainer: {
    alignItems: 'center',
    marginVertical: SPACING.md,
  },
  button: {
    width: '80%',
    height: 50,
    backgroundColor: COLORS.primary.main,
    borderRadius: RADIUS.xl,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  buttonDisabled: {
    backgroundColor: COLORS.primary.light,
    elevation: 0,
  },
  buttonText: {
    color: COLORS.text.light,
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.bold,
  },
  linkText: {
    color: COLORS.primary.main,
    fontWeight: FONT_WEIGHT.bold,
    textDecorationLine: 'underline',
  },
  normalText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.text.secondary,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalWrapper: {
    backgroundColor: COLORS.background.card,
    borderTopLeftRadius: RADIUS.lg,
    borderTopRightRadius: RADIUS.lg,
    padding: SPACING.lg,
  },
  closeButtonWrapper: {
    alignItems: 'flex-end',
    marginBottom: SPACING.sm,
  },
  closeButtonText: {
    color: COLORS.primary.main,
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.bold,
    padding: 5,
  },
  selectedText: {
    color: COLORS.text.primary,
    fontSize: FONT_SIZE.md,
  },
  placeholderText: {
    color: COLORS.text.tertiary,
    fontSize: FONT_SIZE.md,
  },
  formGroup: {
    marginBottom: SPACING.lg,
  },
  inputLabel: {
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.medium,
    color: COLORS.text.secondary,
    marginBottom: SPACING.sm,
  },
  inputHintText: {
    color: COLORS.text.tertiary,
    fontSize: FONT_SIZE.xs,
    marginTop: SPACING.xs,
  },
  linkContainer: {
    marginVertical: SPACING.md,
    alignItems: 'flex-start',
  },
  forgotPasswordContainer: {
    alignSelf: 'flex-end',
    marginTop: SPACING.xs,
    marginBottom: SPACING.lg,
  },
  forgotPasswordText: {
    color: COLORS.primary.main,
    fontSize: FONT_SIZE.sm,
  },
  progressIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: SPACING.lg,
  },
  progressDot: {
    width: 15,
    height: 15,
    borderRadius: RADIUS.round,
    backgroundColor: COLORS.border.main,
  },
  activeDot: {
    backgroundColor: COLORS.primary.main,
  },
  progressLine: {
    height: 3,
    width: 60,
    backgroundColor: COLORS.border.main,
    marginHorizontal: SPACING.xs,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border.main,
    marginBottom: SPACING.sm,
  },
  modalTitle: {
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.text.primary,
  },
  datePickerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: SPACING.lg,
  },
  datePickerColumn: {
    flex: 1,
    marginHorizontal: SPACING.xs,
  },
  datePickerLabel: {
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.medium,
    color: COLORS.text.secondary,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  datePickerScroll: {
    height: 160,
    borderWidth: 1,
    borderColor: COLORS.border.main,
    borderRadius: RADIUS.md,
  },
  datePickerItem: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  datePickerItemSelected: {
    backgroundColor: '#e6efff',
  },
  datePickerText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.text.secondary,
  },
  datePickerTextSelected: {
    color: COLORS.primary.main,
    fontWeight: FONT_WEIGHT.semiBold,
  },
  // New common profile styles
  profileCard: {
    backgroundColor: COLORS.background.card,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border.main,
  },
  profileHeaderSection: {
    backgroundColor: COLORS.background.card,
    padding: SPACING.lg,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border.main,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: RADIUS.round,
    marginBottom: SPACING.sm,
  },
  avatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: RADIUS.round,
    backgroundColor: COLORS.primary.main,
    justifyContent: 'center',
    alignItems: 'center',
  },
  userNameText: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.text.primary,
    marginVertical: SPACING.xs,
  },
  userEmailText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.text.secondary,
    marginBottom: SPACING.md,
  },
  profileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background.card,
    borderWidth: 1,
    borderColor: COLORS.primary.main,
    borderRadius: RADIUS.xl,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    marginVertical: SPACING.sm,
  },
  profileButtonText: {
    color: COLORS.primary.main,
    fontWeight: FONT_WEIGHT.semiBold,
    marginLeft: SPACING.xs,
    fontSize: FONT_SIZE.md,
  },
  sectionTitle: {
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.text.primary,
    marginBottom: SPACING.md,
    marginTop: SPACING.lg,
  },
  infoListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.sm,
  },
  infoIcon: {
    width: 40,
    alignItems: 'center',
  },
  infoTextContainer: {
    marginLeft: SPACING.sm,
    flex: 1,
  },
  infoLabel: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.text.tertiary,
  },
  infoValue: {
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.medium,
    color: COLORS.text.primary,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border.main,
    marginVertical: SPACING.xs,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: SPACING.md,
  },
  primaryButton: {
    backgroundColor: COLORS.primary.main,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: COLORS.text.light,
    fontWeight: FONT_WEIGHT.semiBold,
  },
  secondaryButton: {
    backgroundColor: COLORS.secondary.main,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: COLORS.text.light,
    fontWeight: FONT_WEIGHT.semiBold,
  },
  dangerButton: {
    backgroundColor: COLORS.danger,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  dangerButtonText: {
    color: COLORS.text.light,
    fontWeight: FONT_WEIGHT.semiBold,
    marginLeft: SPACING.xs,
  },
  formField: {
    marginBottom: SPACING.md,
  },
  formInput: {
    backgroundColor: COLORS.background.main,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    fontSize: FONT_SIZE.md,
    color: COLORS.text.primary,
    borderWidth: 1,
    borderColor: COLORS.border.main,
    height: 48,
  },
  formInputError: {
    borderColor: COLORS.danger,
  },
  formLabel: {
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.medium,
    color: COLORS.text.secondary,
    marginBottom: SPACING.xs,
  },
  formError: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.danger,
    marginTop: SPACING.xxs,
  },
});
