spring:
  security:
    web:
      cors:
        enabled: true
      filter:
        order: 1
      authentication:
        enabled: false
    basic:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:carpool_test_e2e}
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_password}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  rabbitmq:
    virtual-host: ${RABBITMQ_VHOST:/}
    exchanges:
      carpool: carpool.topic
    queues:
      notifications: ${QUEUE_NOTIFICATIONS:carpool.notifications}
      rides-created: ${QUEUE_RIDE_CREATED:carpool.rides.created}
      rides-updated: ${QUEUE_RIDE_UPDATED:carpool.rides.updated}
      rides-request: ${QUEUE_REQUEST:carpool.rides.request}
      avaliacoes: ${QUEUE_AVALIACAO:carpool.avaliacao}

supabase:
  api-key: ${SUPABASE_API_KEY:dummy-key-for-testing}
  code: ${SUPABASE_PROJECT_CODE:dummy-project}
  userphotos-bucket-name: ${SUPABASE_USERPHOTOS_BUCKET_NAME:userphotos}

fcm:
  credentials-file: ${FCM_CREDENTIALS_FILE:dummy-credentials.json}
  project-name: ${FCM_PROJECT_NAME:carona-test}
  base-url: ${FCM_BASE_URL:https://fcm.googleapis.com/v1/}

logging:
  level:
    root: INFO
    com.br.puc.carona: INFO
    org.hibernate.SQL: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
