spring:
  application:
    name: carona
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:carpool_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:carpool_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:8080}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.br.puc.carona: ${APP_LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${HIBERNATE_LOG_LEVEL:INFO}
    org.springframework.web: ${SPRING_WEB_LOG_LEVEL:INFO}

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret}