version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: carpool-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-carpool_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-carpool_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
